-- Create a table to store user push notification tokens
CREATE TABLE public.push_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  platform TEXT NOT NULL, -- e.g., 'fcm' for Android, 'apn' for iOS
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- A user can have the same token only once
  UNIQUE (user_id, token)
);

-- Enable RLS
ALTER TABLE public.push_tokens ENABLE ROW LEVEL SECURITY;

-- Policies for push_tokens
-- Users can insert their own tokens
CREATE POLICY "Allow users to insert their own push tokens"
ON public.push_tokens
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- Users can see their own tokens
CREATE POLICY "Allow users to see their own push tokens"
ON public.push_tokens
FOR SELECT
USING (auth.uid() = user_id);

-- Users can delete their own tokens (e.g., on logout)
CREATE POLICY "Allow users to delete their own push tokens"
ON public.push_tokens
FOR DELETE
USING (auth.uid() = user_id);
