-- =====================================================================
-- MIGRAÇÃO DERRADEIRA – Elo App
-- Execute esta migração no editor SQL do Supabase para configurar
-- TUDO o que o aplicativo precisa para funcionar corretamente.
-- Esta migração é idempotente (pode ser executada múltiplas vezes).
-- =====================================================================

-- =====================================================================
-- 1. EXTENSÕES
-- =====================================================================
CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA extensions;

-- =====================================================================
-- 2. TABELAS
-- =====================================================================

-- 2.1 Perfis
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  full_name TEXT,
  avatar_url TEXT,
  bio TEXT,
  interests TEXT[],
  location GEOGRAPHY(Point, 4326),
  birth_date DATE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Caso a tabela já exista sem birth_date, adicionamos a coluna
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema = 'public' AND table_name = 'profiles' AND column_name = 'birth_date'
  ) THEN
    ALTER TABLE public.profiles ADD COLUMN birth_date DATE;
  END IF;
END $$;

-- 2.2 Interações
CREATE TABLE IF NOT EXISTS public.interactions (
  id BIGSERIAL PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  target_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  action TEXT NOT NULL CHECK (action IN ('like', 'dislike')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, target_user_id)
);

-- 2.3 Matches
CREATE TABLE IF NOT EXISTS public.matches (
  id BIGSERIAL PRIMARY KEY,
  user1_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  user2_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user1_id, user2_id)
);

-- 2.4 Mensagens
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGSERIAL PRIMARY KEY,
  match_id BIGINT NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2.5 Push Tokens
CREATE TABLE IF NOT EXISTS public.push_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  token TEXT NOT NULL,
  platform TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, token)
);

-- =====================================================================
-- 3. VIEWS
-- =====================================================================
DROP VIEW IF EXISTS public.profiles_with_age;
CREATE OR REPLACE VIEW public.profiles_with_age AS
SELECT
  *,
  EXTRACT(YEAR FROM AGE(birth_date))::integer AS age
FROM
  public.profiles;

-- =====================================================================
-- 4. ÍNDICES DE PERFORMANCE
-- =====================================================================
CREATE INDEX IF NOT EXISTS idx_interactions_user_id ON public.interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_interactions_target_user_id ON public.interactions(target_user_id);
CREATE INDEX IF NOT EXISTS idx_interactions_user_target ON public.interactions(user_id, target_user_id);
CREATE INDEX IF NOT EXISTS idx_matches_user1_id ON public.matches(user1_id);
CREATE INDEX IF NOT EXISTS idx_matches_user2_id ON public.matches(user2_id);
CREATE INDEX IF NOT EXISTS idx_messages_match_id ON public.messages(match_id);
CREATE INDEX IF NOT EXISTS idx_messages_created_at ON public.messages(match_id, created_at);
CREATE INDEX IF NOT EXISTS idx_push_tokens_user_id ON public.push_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_location ON public.profiles USING GIST(location);

-- =====================================================================
-- 5. FUNÇÕES AUXILIARES
-- =====================================================================

-- 5.1 Contar elementos comuns entre dois arrays
CREATE OR REPLACE FUNCTION count_common_elements(arr1 text[], arr2 text[])
RETURNS integer AS $$
DECLARE
  common_count integer := 0;
  elem text;
BEGIN
  IF arr1 IS NULL OR arr2 IS NULL THEN
    RETURN 0;
  END IF;
  FOREACH elem IN ARRAY arr1
  LOOP
    IF elem = ANY(arr2) THEN
      common_count := common_count + 1;
    END IF;
  END LOOP;
  RETURN common_count;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- =====================================================================
-- 6. TRIGGER: Auto-criar perfil quando um usuário se cadastra
-- =====================================================================

-- Dropar funções existentes para permitir alteração de assinatura
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.handle_interaction(uuid, uuid, text) CASCADE;
DROP FUNCTION IF EXISTS public.get_recommendations(uuid) CASCADE;
DROP FUNCTION IF EXISTS public.get_matches(uuid) CASCADE;
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'preferred_username', NEW.email, NEW.id::text)
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Dropar e recriar o trigger para garantir consistência
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- =====================================================================
-- 7. RPC: handle_interaction (SECURITY DEFINER)
--    Registra like/dislike e cria match se houver reciprocidade
-- =====================================================================
CREATE OR REPLACE FUNCTION handle_interaction(
  p_user_id uuid,
  p_target_user_id uuid,
  p_action text
)
RETURNS boolean AS $$
DECLARE
  is_match boolean := false;
BEGIN
  -- Inserir a interação
  INSERT INTO public.interactions (user_id, target_user_id, action)
  VALUES (p_user_id, p_target_user_id, p_action)
  ON CONFLICT (user_id, target_user_id) 
  DO UPDATE SET action = EXCLUDED.action, created_at = NOW();

  -- Se for 'like', verificar reciprocidade
  IF p_action = 'like' THEN
    IF EXISTS (
      SELECT 1
      FROM public.interactions
      WHERE user_id = p_target_user_id
        AND target_user_id = p_user_id
        AND action = 'like'
    ) THEN
      is_match := true;

      -- Inserir match (LEAST/GREATEST garante unicidade)
      INSERT INTO public.matches (user1_id, user2_id)
      SELECT
        LEAST(p_user_id, p_target_user_id),
        GREATEST(p_user_id, p_target_user_id)
      ON CONFLICT (user1_id, user2_id) DO NOTHING;
    END IF;
  END IF;

  RETURN is_match;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================================
-- 8. RPC: get_recommendations (SECURITY DEFINER)
--    Retorna até 20 perfis recomendados com score baseado em
--    distância (60%) e interesses comuns (40%)
-- =====================================================================
CREATE OR REPLACE FUNCTION get_recommendations(current_user_id uuid)
RETURNS TABLE(
  id uuid,
  username text,
  full_name text,
  avatar_url text,
  bio text,
  interests text[],
  age integer,
  recommendation_score float
) AS $$
DECLARE
  current_user_location geography;
  max_distance float := 50000; -- 50km
BEGIN
  -- Obter localização do usuário atual
  SELECT p.location INTO current_user_location
  FROM public.profiles p
  WHERE p.id = current_user_id;

  RETURN QUERY
  WITH user_interests AS (
    SELECT p_inner.interests
    FROM public.profiles p_inner
    WHERE p_inner.id = current_user_id
  ),
  scores AS (
    SELECT
      p.id,
      p.username,
      p.full_name,
      p.avatar_url,
      p.bio,
      p.interests,
      EXTRACT(YEAR FROM AGE(p.birth_date))::integer AS age,
      CASE
        WHEN current_user_location IS NOT NULL AND p.location IS NOT NULL THEN
          (1 - LEAST(ST_Distance(current_user_location, p.location) / max_distance, 1.0))
        ELSE
          0.0
      END AS distance_score,
      count_common_elements(ui.interests, p.interests) AS interest_score
    FROM
      public.profiles p, user_interests ui
    WHERE
      p.id != current_user_id
      -- Excluir perfis já interagidos
      AND NOT EXISTS (
        SELECT 1 FROM public.interactions i
        WHERE i.user_id = current_user_id AND i.target_user_id = p.id
      )
      -- Excluir perfis que já são match
      AND NOT EXISTS (
        SELECT 1 FROM public.matches m
        WHERE (m.user1_id = current_user_id AND m.user2_id = p.id)
           OR (m.user2_id = current_user_id AND m.user1_id = p.id)
      )
  )
  SELECT
    s.id,
    s.username,
    s.full_name,
    s.avatar_url,
    s.bio,
    s.interests,
    s.age,
    (COALESCE(s.distance_score, 0) * 0.6 + COALESCE(s.interest_score, 0) * 0.4)::float AS recommendation_score
  FROM
    scores s
  ORDER BY
    recommendation_score DESC
  LIMIT 20;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================================
-- 9. RPC: get_matches (SECURITY DEFINER)
--    Retorna todos os matches do usuário com informações do outro perfil
-- =====================================================================
CREATE OR REPLACE FUNCTION get_matches(p_user_id uuid)
RETURNS TABLE (
  match_id bigint,
  other_user_id uuid,
  other_user_full_name text,
  other_user_avatar_url text
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    m.id AS match_id,
    CASE
      WHEN m.user1_id = p_user_id THEN m.user2_id
      ELSE m.user1_id
    END AS other_user_id,
    p.full_name AS other_user_full_name,
    p.avatar_url AS other_user_avatar_url
  FROM
    public.matches m
  JOIN
    public.profiles p ON p.id = (
      CASE
        WHEN m.user1_id = p_user_id THEN m.user2_id
        ELSE m.user1_id
      END
    )
  WHERE
    (m.user1_id = p_user_id OR m.user2_id = p_user_id)
  ORDER BY
    m.created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- =====================================================================
-- 10. ROW LEVEL SECURITY (RLS)
-- =====================================================================

-- Habilitar RLS em todas as tabelas
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.push_tokens ENABLE ROW LEVEL SECURITY;

-- ---------- PROFILES ----------

DROP POLICY IF EXISTS "Users can view all profiles." ON public.profiles;
CREATE POLICY "Users can view all profiles."
ON public.profiles FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Users can update their own profile." ON public.profiles;
CREATE POLICY "Users can update their own profile."
ON public.profiles FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can delete their own profile." ON public.profiles;
CREATE POLICY "Users can delete their own profile."
ON public.profiles FOR DELETE
TO authenticated
USING (auth.uid() = id);

-- Permitir INSERT do trigger (service role) e do próprio usuário
DROP POLICY IF EXISTS "Service role can insert profiles." ON public.profiles;
CREATE POLICY "Service role can insert profiles."
ON public.profiles FOR INSERT
WITH CHECK (true);

-- ---------- INTERACTIONS ----------

DROP POLICY IF EXISTS "Users can insert their own interactions." ON public.interactions;
CREATE POLICY "Users can insert their own interactions."
ON public.interactions FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can only see their own interactions." ON public.interactions;
CREATE POLICY "Users can only see their own interactions."
ON public.interactions FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- ---------- MATCHES ----------

-- Remover policies conflitantes anteriores
DROP POLICY IF EXISTS "Block all client-side modifications on matches" ON public.matches;
DROP POLICY IF EXISTS "Users can view their own matches." ON public.matches;
DROP POLICY IF EXISTS "Block client-side insert on matches" ON public.matches;
DROP POLICY IF EXISTS "Block client-side update on matches" ON public.matches;
DROP POLICY IF EXISTS "Block client-side delete on matches" ON public.matches;

-- SELECT: Usuário pode ver seus próprios matches
CREATE POLICY "Users can view their own matches."
ON public.matches FOR SELECT
TO authenticated
USING (auth.uid() = user1_id OR auth.uid() = user2_id);

-- Bloquear INSERT/UPDATE/DELETE direto do cliente
-- (matches são criados pela função handle_interaction com SECURITY DEFINER)
CREATE POLICY "Block client-side insert on matches"
ON public.matches FOR INSERT
TO authenticated
WITH CHECK (false);

CREATE POLICY "Block client-side update on matches"
ON public.matches FOR UPDATE
TO authenticated
USING (false)
WITH CHECK (false);

CREATE POLICY "Block client-side delete on matches"
ON public.matches FOR DELETE
TO authenticated
USING (false);

-- ---------- MESSAGES ----------

DROP POLICY IF EXISTS "Users can view messages in their own matches." ON public.messages;
CREATE POLICY "Users can view messages in their own matches."
ON public.messages FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM public.matches
    WHERE matches.id = messages.match_id
      AND (matches.user1_id = auth.uid() OR matches.user2_id = auth.uid())
  )
);

DROP POLICY IF EXISTS "Users can insert messages in their own matches." ON public.messages;
CREATE POLICY "Users can insert messages in their own matches."
ON public.messages FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() = sender_id
  AND EXISTS (
    SELECT 1 FROM public.matches
    WHERE matches.id = messages.match_id
      AND (matches.user1_id = auth.uid() OR matches.user2_id = auth.uid())
  )
);

-- ---------- PUSH TOKENS ----------

DROP POLICY IF EXISTS "Allow users to insert their own push tokens" ON public.push_tokens;
CREATE POLICY "Allow users to insert their own push tokens"
ON public.push_tokens FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow users to see their own push tokens" ON public.push_tokens;
CREATE POLICY "Allow users to see their own push tokens"
ON public.push_tokens FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow users to delete their own push tokens" ON public.push_tokens;
CREATE POLICY "Allow users to delete their own push tokens"
ON public.push_tokens FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- =====================================================================
-- 11. REALTIME – Habilitar para mensagens
-- =====================================================================
-- Descomente se ainda não habilitou:
-- ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;

-- =====================================================================
-- 12. STORAGE BUCKET – Avatares
-- =====================================================================
-- Execute manualmente no painel do Supabase Storage:
-- 1. Criar bucket 'avatars' (público)
-- 2. Adicionar policy: INSERT para authenticated (user can upload to their own folder)
-- 3. Adicionar policy: SELECT público (anyone can view)
-- 4. Adicionar policy: UPDATE para authenticated (user can update their own files)

-- =====================================================================
-- FIM DA MIGRAÇÃO DERRADEIRA
-- =====================================================================
